---
- hosts: localhost
  connection: local
  ignore_errors: yes
  
  tasks:
  - name: install iTerm2
    package: 
      name: iTerm2

  - name: install spectacle
    package: 
      name: spectacle

  - name: install karabiner
    package:
      name: karabiner-elements

  - name: install nodejs
    package:
      name: node

  - name: install emacs
    package:
      name: emacs

  - name: install packages for doom
    package:
      name: 
        - ripgrep 
        - coreutils 
        - fd

  - name: install powerline-fonts
    script: powerline-fonts.sh
