---
- hosts: localhost
  connection: local
  ignore_errors: yes
  
  tasks:
  - name: Install iTerm2
    package: 
      name: iTerm2

  - name: Install spectacle
    package: 
      name: spectacle

  - name: Install karabiner
    package:
      name: karabiner-elements

  - name: Install hammerspoon
    package:
      name: hammerspoon

  - name: Download hammerspoon conifg
    shell: | 
      cd /tmp
      git git@github.com:witoldzol/hammerspoon_config.git
      mv /tmp/hammerspoon_config/init.lua ~/.hammerspoon
      rm -rf /tmp/hammerspoon_config

  - name: Install VSCode
    package: 
      name: visual-studio-code

  - name: Install jq (json formatter)
    package: 
      name: jq

  - name: Install alfred
    package:
      name: alfred

  - name: Install nodejs
    package:
      name: node

  - name: Install emacs
    shell: brew install emacs --cask

  - name: Install packages for doom
    package:
      name: 
        - ripgrep 
        - coreutils 
        - fd

  - name: Check if DOOM is installed
    stat:
      path: ~/.emacs.d/bin/doom
    register: stat_result

  - name: Install DOOM
    shell: | 
      git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
      ~/.emacs.d/bin/doom install -y
    when: not stat_result.stat.exists

  - name: Copy custom Doom config
    shell: | 
      cd /tmp
      git clone git@github.com:witoldzol/emacs_doom_config.git
      mv /tmp/emacs_doom_config/* ~/.doom.d/
      rm -rf /tmp/emacs_doom_config

  - name: Reload doom with the new config settings
    shell: | 
      cd ~/.emacs.d/bin
      ./doom sync

  - name: Check if powerline-fonts are installed
    stat:
      path: /Users/witold/Library/Fonts/ProFont For Powerline.ttf
    register: font_result

  - name: install powerline-fonts
    script: powerline-fonts.sh
    when: not font_result.stat.exists

  - name: Install custom shortucts for MAC OS
    shell: |
      cd /tmp
      git clone git@github.com:fkchang/emacs-keybindings-in-osx.git
      ./emacs-keybindings-in-osx/install.sh
      rm -rf emacs-keybindings-in-osx
    tags:
      - shortcuts
