---
- hosts: localhost
  connection: local
  ignore_errors: yes
  
  tasks:
  - name: install packages
    package: 
      name: 
        - iTerm2
  - name: install powerline-fonts
    shell: powerline-fonts.sh
